### ISSUE TITLE
Porting to BCC32 (Borland Compiler) C++11 implementation

### ISSUE THREAD

**Issue by GermanAizek** [rekola/simplexlsx#3]
@rekola,
I rewrote entire library in C++98, can you include my commits in separate branch `cpp98` or `C++98`? I'm not one who needed support up before C++11 standard version.

**Comment by rekola** [comment]
Why are these changes necessary?

If we were to start improving the library in Github, the work should start by creating test cases for all the parts that we are going to modify. Also CI using Github Actions would be useful.

**Comment by GermanAizek** [comment]
> Why are these changes necessary?

initially, I needed this library, but I have an old compiler. I ported for old compilers and immediately sent PR for those who need support before C++11 for old compilers.

**Comment by rekola** [comment]
You should switch to a newer compiler. I'm sorry, but I cannot accept these these changes. It is not possible for me to test them since I do not have access to Borland commpiler.
